version: 2
jobs:
  build:
    docker:
      - image: themattrix/tox
    working_directory: ~/django-formidable
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install --user tox
      - run:
          name: Run the test suite
          command: tox -r

  docs:
    working_directory: ~/django-formidable
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run:
          name: Check Python version & install Python dependencies
          command: |
            python --version
            sudo apt update && sudo apt install python-pip python-dev
      - run:
          name: Run Sphinx doc tests using tox
          command: |
            pip install --user tox
            ~/.local/bin/tox -e docs

workflows:
  version: 2
  tests:
    jobs:
      # Run Python / Django tests
      - build
      # Build docs (requires npm/node)
      - docs
