version: 2
jobs:
  build:
    docker:
      - image: themattrix/tox
      - image: circleci/postgres:latest
        environment:
          POSTGRES_HOST_AUTH_METHOD: trust
    working_directory: ~/django-formidable
    steps:
      - run:
          name: "Update APT stuff"
          command: "apt-get update"
      - run:
          name: "Install postgresql-common Debian package"
          command: "apt-get install -y postgresql-common"
      - checkout
      - run:
          name: Run the test suite
          command: tox -r

  docs:
    working_directory: ~/django-formidable
    docker:
      - image: circleci/node:lts-buster
    steps:
      - checkout
      - run:
          name: Check Python version & install Python dependencies
          command: |
            python3 --version
            sudo apt update && sudo apt install python-pip python-dev
      - run:
          name: Run Sphinx doc tests using tox
          command: |
            pip install --user tox
            ~/.local/bin/tox -e docs

workflows:
  version: 2
  tests:
    jobs:
      # Run Python / Django tests
      - build
      # Build docs (requires npm/node)
      - docs
